name: skyteresultater_app
description: En app for å registrere skyteresultater.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_material: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true